### ISSUE TITLE
콘솔 오류

### ISSUE THREAD

**Issue by minejango2** [noonmaru/farm#3]
Paper 1.16.2 v187 에서 구동하였는데 밑 오류가 나면서 플러그인이 비활성화됩니다.

[17:53:44 ERROR]: Error occurred while enabling Farm v0.1 (Is it up to date?)
java.lang.NoClassDefFoundError: kotlin/jdk7/AutoCloseableKt
        at com.github.noonmaru.farm.internal.FarmIOSQLite.createTables(FarmIO.kt:54) ~[?:?]
        at com.github.noonmaru.farm.internal.FarmIOSQLite.<init>(FarmIO.kt:41) ~[?:?]
        at com.github.noonmaru.farm.internal.FarmInternal.initialize$farm(FarmInternal.kt:14) ~[?:?]
        at com.github.noonmaru.farm.plugin.FarmPlugin.onEnable(FarmPlugin.kt:23) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.2.jar:git-Paper-187]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.2.jar:git-Paper-187]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.2.jar:git-Paper-187]
        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:499) ~[patched_1.16.2.jar:git-Paper-187]
        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:413) ~[patched_1.16.2.jar:git-Paper-187]
        at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:468) ~[patched_1.16.2.jar:git-Paper-187]
        at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:241) ~[patched_1.16.2.jar:git-Paper-187]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939) ~[patched_1.16.2.jar:git-Paper-187]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.2.jar:git-Paper-187]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_202]
Caused by: java.lang.ClassNotFoundException: kotlin.jdk7.AutoCloseableKt
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_202]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:171) ~[patched_1.16.2.jar:git-Paper-187]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[patched_1.16.2.jar:git-Paper-187]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_202]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_202]
        ... 14 more
[17:53:44 INFO]: [Farm] Disabling Farm v0.1
[17:53:44 ERROR]: Error occurred while disabling Farm v0.1 (Is it up to date?)
kotlin.UninitializedPropertyAccessException: lateinit property io has not been initialized
        at com.github.noonmaru.farm.internal.FarmInternal.disable$farm(FarmInternal.kt:30) ~[?:?]
        at com.github.noonmaru.farm.plugin.FarmPlugin.onDisable(FarmPlugin.kt:34) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.16.2.jar:git-Paper-187]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:415) ~[patched_1.16.2.jar:git-Paper-187]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:516) ~[patched_1.16.2.jar:git-Paper-187]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:384) ~[patched_1.16.2.jar:git-Paper-187]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.2.jar:git-Paper-187]
        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:499) ~[patched_1.16.2.jar:git-Paper-187]
        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:413) ~[patched_1.16.2.jar:git-Paper-187]
        at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:468) ~[patched_1.16.2.jar:git-Paper-187]
        at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:241) ~[patched_1.16.2.jar:git-Paper-187]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939) ~[patched_1.16.2.jar:git-Paper-187]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.2.jar:git-Paper-187]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_202]

다운받아진 플러그인이 tap 2.8.8, protocolLib 4.5.1, Kotlin 1.4.0, worldedit 7.2.0 beta4 가 있습니다.
API가 1.15.2인거 같아서 1.15.2로 구동했더니

[17:57:19 ERROR]: Error occurred while enabling Farm v0.1 (Is it up to date?)
java.lang.NoClassDefFoundError: kotlin/jdk7/AutoCloseableKt
        at com.github.noonmaru.farm.internal.FarmIOSQLite.createTables(FarmIO.kt:54) ~[?:?]
        at com.github.noonmaru.farm.internal.FarmIOSQLite.<init>(FarmIO.kt:41) ~[?:?]
        at com.github.noonmaru.farm.internal.FarmInternal.initialize$farm(FarmInternal.kt:14) ~[?:?]
        at com.github.noonmaru.farm.plugin.FarmPlugin.onEnable(FarmPlugin.kt:23) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Paper-385]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.15.2.jar:git-Paper-385]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.15.2.jar:git-Paper-385]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:472) ~[patched_1.15.2.jar:git-Paper-385]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:386) ~[patched_1.15.2.jar:git-Paper-385]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:488) ~[patched_1.15.2.jar:git-Paper-385]
        at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.15.2.jar:git-Paper-385]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:909) ~[patched_1.15.2.jar:git-Paper-385]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_202]
Caused by: java.lang.ClassNotFoundException: kotlin.jdk7.AutoCloseableKt
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_202]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:171) ~[patched_1.15.2.jar:git-Paper-385]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[patched_1.15.2.jar:git-Paper-385]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_202]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_202]
        ... 13 more
[17:57:19 INFO]: [Farm] Disabling Farm v0.1
[17:57:19 ERROR]: Error occurred while disabling Farm v0.1 (Is it up to date?)
kotlin.UninitializedPropertyAccessException: lateinit property io has not been initialized
        at com.github.noonmaru.farm.internal.FarmInternal.disable$farm(FarmInternal.kt:30) ~[?:?]
        at com.github.noonmaru.farm.plugin.FarmPlugin.onDisable(FarmPlugin.kt:34) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.15.2.jar:git-Paper-385]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:415) ~[patched_1.15.2.jar:git-Paper-385]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:516) ~[patched_1.15.2.jar:git-Paper-385]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:384) ~[patched_1.15.2.jar:git-Paper-385]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.15.2.jar:git-Paper-385]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:472) ~[patched_1.15.2.jar:git-Paper-385]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:386) ~[patched_1.15.2.jar:git-Paper-385]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:488) ~[patched_1.15.2.jar:git-Paper-385]
        at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.15.2.jar:git-Paper-385]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:909) ~[patched_1.15.2.jar:git-Paper-385]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_202]

라고 뜹니다.

**Comment by noonmaru** [comment]
https://github.com/noonmaru/kotlin-plugin/releases/tag/1.0

이 버전이 필요한데 빌드되어있지 않아 직접 빌드하셔야할듯합니다.

**Comment by minejango2** [comment]
Kotlin 플러그인을 햇갈렸습니다. 각별님이 따로 만들어 놓으신 것이 있는지 몰랐습니다. 계속 이름만 같고 다른 플러그인을 사용하고 있었네요.

각별님이 만든 Kotlin 플러그인을 사용하니 1.0(intelliJ IDEA 빌드, plugin.yml은 나중에 따로 넣음)과 1.4.0 모두 잘 작동하였습니다. 근데 버그가 조금 있습니다(1.15.2와 1.16.2에서 테스트해봤습니다).

참고로 Kotlin 1.0과 1.4.0 전부에서 발생하였습니다.

공통 버그
1. 가문비나무 묘목을 들고 /farm animate를 치면 아무 메시지와 아무 콘솔 명령어도 나오지 않으면서 묘목에 인챈트가 안됩니다.
(1.15.2에서는 아예 묘목으로 인식을 안하고 아니라는 메시지가 뜹니다.)
2. 모든 작물의 시간이 뜨지 않습니다.(Shift + 우클릭해도 안됩니다)
3. 경작지 위에서 나무가 자라면 나무 블록이 경작지를 흙으로 만듭니다.
4. 처음 설치할 때 기름진 경작지가 마른 경작지로 변합니다.

1.16.2 버그
1. 1.16의 진홍빛 균과 뒤틀린 균은 아직 안됩니다.(도움을 드리고자 말해드리자면 진홍빛 균은 진홍빛 네서체 위에서만, 뒤틀린 균은 뒤틀린 네사체 위에서만 자랍니다(뼛가루 포함). 또한 모든 월드에서 자랍니다.)

또한 질문이 있는데, 작물이 자라는 시간 설정 단위가 무엇인가요?

**Comment by minejango2** [comment]
+ Shift 우클릭 할 시

[22:19:11 ERROR]: Could not pass event PlayerInteractEvent to Farm v0.1
java.lang.NoSuchMethodError: com.github.noonmaru.tap.fake.FakeSupportKt.setPosition(Lorg/bukkit/entity/Entity;Lorg/bukkit/Location;)V
        at com.github.noonmaru.farm.internal.timer.CropTimeViewer.updatePosition(CropTimeViewer.kt:94) ~[?:?]
        at com.github.noonmaru.farm.internal.timer.CropTimeViewer.updatePosition$default(CropTimeViewer.kt:90) ~[?:?]
        at com.github.noonmaru.farm.internal.timer.CropTimeViewer.<init>(CropTimeViewer.kt:70) ~[?:?]
        at com.github.noonmaru.farm.internal.FarmManagerImpl.addTimer$farm(FarmManagerImpl.kt:40) ~[?:?]
        at com.github.noonmaru.farm.internal.EventListener.onPlayerInteract(EventListener.kt:151) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor4.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.2.jar:git-Paper-187]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.2.jar:git-Paper-187]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.2.jar:git-Paper-187]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.2.jar:git-Paper-187]
        at org.bukkit.craftbukkit.v1_16_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:503) ~[patched_1.16.2.jar:git-Paper-187]
        at net.minecraft.server.v1_16_R2.PlayerInteractManager.a(PlayerInteractManager.java:459) ~[patched_1.16.2.jar:git-Paper-187]
        at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1449) ~[patched_1.16.2.jar:git-Paper-187]
        at net.minecraft.server.v1_16_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[patched_1.16.2.jar:git-Paper-187]
        at net.minecraft.server.v1_16_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.16.2.jar:git-Paper-187]
        at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.2.jar:git-Paper-187]
        at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[patched_1.16.2.jar:git-Paper-187]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.2.jar:git-Paper-187]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.2.jar:git-Paper-187]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.2.jar:git-Paper-187]
        at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1135) ~[patched_1.16.2.jar:git-Paper-187]
        at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1128) ~[patched_1.16.2.jar:git-Paper-187]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.2.jar:git-Paper-187]
        at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:1089) ~[patched_1.16.2.jar:git-Paper-187]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:1003) ~[patched_1.16.2.jar:git-Paper-187]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.2.jar:git-Paper-187]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_202]

에러가 뜹니다.

**Comment by noonmaru** [comment]
https://github.com/noonmaru/tap/releases/tag/2.3.3

이 버전의 Tap을 빌드해서 사용해보세요

버그는 제보해주신 내용 참고하여 곧 픽스하겠습니다.

감사합니다

**Comment by minejango2** [comment]
[23:30:18 ERROR]: Could not pass event PlayerInteractEvent to Farm v0.1
java.lang.NoClassDefFoundError: Could not initialize class com.github.noonmaru.tap.fake.FakeSupportKt
        at com.github.noonmaru.farm.internal.timer.CropTimeViewer.updatePosition(CropTimeViewer.kt:94) ~[?:?]
        at com.github.noonmaru.farm.internal.timer.CropTimeViewer.updatePosition$default(CropTimeViewer.kt:90) ~[?:?]
        at com.github.noonmaru.farm.internal.timer.CropTimeViewer.<init>(CropTimeViewer.kt:70) ~[?:?]
        at com.github.noonmaru.farm.internal.FarmManagerImpl.addTimer$farm(FarmManagerImpl.kt:40) ~[?:?]
        at com.github.noonmaru.farm.internal.EventListener.onPlayerInteract(EventListener.kt:151) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor4.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.2.jar:git-Paper-187]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.2.jar:git-Paper-187]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.2.jar:git-Paper-187]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.2.jar:git-Paper-187]
        at org.bukkit.craftbukkit.v1_16_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:503) ~[patched_1.16.2.jar:git-Paper-187]
        at net.minecraft.server.v1_16_R2.PlayerInteractManager.a(PlayerInteractManager.java:459) ~[patched_1.16.2.jar:git-Paper-187]
        at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1449) ~[patched_1.16.2.jar:git-Paper-187]
        at net.minecraft.server.v1_16_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[patched_1.16.2.jar:git-Paper-187]
        at net.minecraft.server.v1_16_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.16.2.jar:git-Paper-187]
        at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.2.jar:git-Paper-187]
        at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[patched_1.16.2.jar:git-Paper-187]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.2.jar:git-Paper-187]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.2.jar:git-Paper-187]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.2.jar:git-Paper-187]
        at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1135) ~[patched_1.16.2.jar:git-Paper-187]
        at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1128) ~[patched_1.16.2.jar:git-Paper-187]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.2.jar:git-Paper-187]
        at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:1089) ~[patched_1.16.2.jar:git-Paper-187]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:1003) ~[patched_1.16.2.jar:git-Paper-187]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.2.jar:git-Paper-187]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_202]

시간 보려고 하니까 오류 또나는거 보니 제가 tap 플러그인 빌드를 잘못한거 같네요(프로그래밍의 기초도 거의 모르는지라... 빌드할 때 plugin.yml에서 이름과 버전, Main이 옮겨지지 않은거 보면...) 시간이 보여지지 않는 버그를 제외하고 나머지 버그가 고쳐지면 알아서 이슈 닫겠습니다.

**Comment by minejango2** [comment]
+tap이 2.3.3인 상태에서는 1.15.2에서는 작동합니다. 여러번 귀찮게 해서 죄송합니다.

**Comment by zlfn** [comment]
기름진 경작지가 마른경작지로 바뀌는건 randomTickSpeed가 0이 아니었던게 아닐까요?

**Comment by minejango2** [comment]
따로 막아놓은것인 줄 알았습니다.
막을 필요가 없긴 하네요.
